/**
 * Local dev setup: writes .env with crypto-strong secrets, starts Docker, prisma db push, seed.
 * Run: npm run setup
 * Regenerate .env: npm run setup -- --force
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const envPath = path.join(root, ".env");
const force = process.argv.includes("--force");

function randHex(bytes) {
  return crypto.randomBytes(bytes).toString("hex");
}

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { cwd: root, encoding: "utf8", shell: true, ...opts });
  return r;
}

/** Stream output to terminal (Docker/Prisma can take minutes; inherit avoids silent hangs). */
function runInherit(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { cwd: root, stdio: "inherit", shell: true, ...opts });
}

function writeEnv() {
  const jwt = randHex(32);
  const enc = randHex(32);
  const trade = randHex(16);
  const csrf = randHex(32);

  const content = `# Generated by npm run setup (${new Date().toISOString()})
NODE_ENV=development
APP_URL=http://localhost:3000
FRONTEND_URL=http://localhost:3000
PORT=4000

DATABASE_URL=postgresql://postgres:postgres@localhost:5432/roblox_gamble?schema=public
REDIS_URL=redis://127.0.0.1:6379

JWT_SECRET=${jwt}
JWT_ACCESS_TTL_SEC=900
JWT_REFRESH_TTL_SEC=1209600

ENCRYPTION_KEY=${enc}
TRADE_HMAC_SECRET=${trade}
CSRF_SECRET=${csrf}

BIO_CHALLENGE_TTL_SEC=900
TRADE_SESSION_TTL_SEC=2700

HOUSE_TAX_PERCENT=5
JACKPOT_MIN_DEPOSIT=50
COINFLIP_MIN_VALUE=100
COINFLIP_ROOM_MINUTES=5
JACKPOT_ROUND_SECONDS=120
JACKPOT_MAX_POT=1000000

BLOCK_VPN=false
MOCK_ROBLOX_TRADES=true

NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_SOCKET_URL=http://127.0.0.1:4000
`;

  fs.writeFileSync(envPath, content, "utf8");
  console.log("Wrote .env with generated secrets (see YOU_MUST_DO_BIO.txt for login & DB steps).");
}

console.log("Roblox GAMBLE — local setup\n");

if (fs.existsSync(envPath) && !force) {
  console.log(".env already exists. Skipping .env generation.");
  console.log("To regenerate .env (WIPES Roblox ID/secret lines if you re-run write): npm run setup -- --force\n");
} else {
  writeEnv();
}

console.log("Starting Postgres + Redis (Docker)...");
const docker = runInherit("docker", ["compose", "up", "-d"], { cwd: root });
if (docker.status !== 0) {
  console.error("docker compose failed (see output above)");
  console.error(
    "\nIf Docker is not installed or not running: install Docker Desktop, start it, then run: docker compose up -d\n",
  );
} else {
  console.log("Docker services started (or already running).\n");
}

console.log("Prisma generate + db push...");
const gen = runInherit("npm", ["run", "db:generate"], { cwd: root });
if (gen.status !== 0) {
  process.exit(1);
}
const push = runInherit("npm", ["run", "db:push"], { cwd: root });
if (push.status !== 0) {
  console.error("\nIf DB connection failed: wait a few seconds after Docker starts, then run: npm run db:push\n");
  process.exit(1);
}
console.log("Database schema applied.\n");

console.log("Seeding...");
const seed = runInherit("npm", ["run", "db:seed"], { cwd: root });
if (seed.status !== 0) {
  console.warn("Seed exited non-zero (may be ok if seed already ran).");
} else {
  console.log("Seed complete.\n");
}

console.log("Done. Next: ensure DATABASE_URL/REDIS_URL work, then npm run dev");
console.log("Read YOU_MUST_DO_BIO.txt for bio login and bot setup.\n");
